MCTS:
  NUM_SIMULATION_PER_STEP: 16
SELF_PLAY:
  GAME_PER_ITER: 32
  BATCH_SIZE: 4
  NUM_WORKER: 4
GAME:
  BOARD_SIZE: 8

SOLVER:
  NUM_ITERS: 10
  SAVE_CHECKPOINT_FREQ: 10
  NUM_EPOCHS: 10
MATCH:
  NUM_MATCHES: 64
DIRS:
  OUTPUTS: /home/hieu123/alpha_zero_mp/runs/