MCTS:
  NUM_SIMULATION_PER_STEP: 32
SELF_PLAY:
  GAME_PER_ITER: 128
  BATCH_SIZE: 8
  NUM_WORKER: 4
GAME:
  BOARD_SIZE: 8
SOLVER:
  NUM_ITERS: 25
  NUM_EPOCHS: 10
  BATCH_SIZE: 64
  SAVE_CHECKPOINT_FREQ: 5
DIRS:
  OUTPUTS: "/home/ad/Documents/runs"