MCTS:
  NUM_SIMULATION_PER_STEP: 64
  C_PUCT: 1.0
  DIRICHLET_ALPHA: 0.03
  DIRICHLET_WEIGHT: 0.1

SELF_PLAY:
  GAME_PER_ITER: 128
  BATCH_SIZE: 4
  NUM_WORKER: 8
  VERBOSE_FREQ: 32

MATCH:
  NUM_MATCHES: 64
  NUM_WORKERS: 8
  VERBOSE_FREQ: 8

GAME:
  BOARD_SIZE: 8

MODEL:
  NAME: "Resnet"
  BASE_CHANNELS: 512
  BOTTLENECK_CHANNELS: 256
  NUM_BLOCKS: 8
  DROP_RATE: 0.3

DATA:
  HISTORY_LENGTH: 25

SOLVER:
  NUM_ITERS: 200
  SAVE_LAST_ONLY: True
  NUM_EPOCHS: 10
  BATCH_SIZE: 64
  UPDATE_THRESH: 0.6

DIRS:
  OUTPUTS: /home/hieu123/alpha_zero_mp2/runs/