MCTS:
  NUM_SIMULATION_PER_STEP: 64
  C_PUCT: 1.0
  DIRICHLET_ALPHA: 0.03
  DIRICHLET_WEIGHT: 0.0
DEVICE: "cpu"
GAME:
  BOARD_SIZE: 8
DEMO:
  CHECKPOINT: "../pretrained_models/exp2_local_iter_037_epoch_010_p_loss_0.5376_v_loss_0.1458.pth"
  HUMAN_PLAYERS: [1]